external_components:
  - source:
      type: local
      path: esphome/components

logger:
  level: DEBUG

esphome:
  name: xye-heatpump-test
  platform: ESP32
  board: esp32dev
  build_path: .build/xye_heatpump_test

xye_heatpump:
  flow_control_pin: GPIO33

uart:
  tx_pin: GPIO32
  rx_pin: GPIO35
  baud_rate: 1200

binary_sensor:
sensor:
